service: cinematic
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  timeout: 10
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/server.handler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET

    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      AUTH_API_KEY: ${env:AUTH_API_KEY}

plugins:
  - serverless-plugin-typescript

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
