INSERT INTO users(name,email,password,country) VALUES ('sumanbiswas','suman@gmail.com','suman007','India');

INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Intersteller',NULL,'Christopher Nolan',NULL,8.5,2014,'Science Fiction','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_interstellar.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Fight Club',NULL,'David Fincher',NULL,8,1999,'Thriller','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_fight_club.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'La La Land',NULL,'Damien Chazelle',NULL,8.5,2016,'Romance','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_la_la_land.webp');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'The Matrix',NULL,'Lana Wachowski',NULL,8,1999,'Science Fiction','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_the_matrix.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Django Unchained',NULL,'Quentien Tarantino',NULL,8.5,2012,'Western','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_django_unchained.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'The Good The Bad and The Ugly',NULL,'Client Eastwood',NULL,8,1975,'Western','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_the_good_the_bad_ugly.webp');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Forrest Gump',NULL,'Robert Zemeckis',NULL,8.5,1994,'Drama','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_forrest_gump.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Inception',NULL,'Christopher Nolan',NULL,8.5,2010,'Science Fiction','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/poster_inception.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Mulholland Drive','Rita, a dark-haired amnesiac, and Betty, a perky blonde actress, team up to find clues related to Rita''s accident and ascertain her true identity.','David Lynch','Naomi Watts, Laurra Harrings',8,2001,'Thriller','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/ed7d10be1071dcd976f8f170648efe3f.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Green Book','Amidst rampant racism in the 1960s southern America, an African American pianist hires an Italian American bouncer to drive him through his venues. They come closer in the course of their journey.','Peter Farrelly','Viggo Mortensen,  Mahershala Ali, Nick Vallelonga',8.5,2018,'Drama','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/83ab4b0d0da38ee54fe01bd125800092.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'Buffalo ''66','Billy kidnaps a young dancer, Layla, and asks her to pretend to be his wife so that he can please his parents. While Layla is initially hesitant, she falls in love with him.','Vincent Gallo','Vincent Gallo, Christina Ricci',7.5,1998,'Drama','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/1333d47e3ae881efc6a8b4185403f08c.jpg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'American Psyco','Patrick Bateman, a wealthy investment banker, hides his psychopathic ego from his friends. Later, his illogical fantasies escalate and he submits to an uncontrollable bloodlust.','Mary Harron','Christian Bale',8.5,2000,'Thriller','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/images.jpeg');
INSERT INTO movies("userId",name,description,director,casts,rating,release,type,image) VALUES (1,'1917','Two soldiers, assigned the task of delivering a critical message to another battalion, risk their lives for the job in order to prevent them from stepping right into a deadly ambush.','Sam Mendes','George MacKay, Dean-Charles',8,2019,'Action','https://movizine-imageupload.s3.ap-south-1.amazonaws.com/e080f41168a8ef24ba80c213eed49026.jpg');
